schema_version: 1

context:
  version: "2.2.8"
  python_min: "3.9"

package:
  name: "func-adl-xaod"
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/func-adl-xaod/func_adl_xaod-${{ version }}.tar.gz
  sha256: dd871a4818e6e78b7359153c98d7992da8d01702311ee82ec222594c383df7c8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - requests
    - retry
    - jinja2
    - qastle
    - func-adl >3.4

tests:
  - python:
      imports:
        - func_adl_xAOD
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: MIT
  license_file: LICENSE
  summary: Backend that converts qastle to run on an ATLAS xAOD backend
  description: |
    Functional Analysis Description Language backend for accessing ATLAS xAOD files.
  homepage: https://github.com/iris-hep/func_adl_xAOD
  repository: https://github.com/iris-hep/func_adl_xAOD
  documentation: https://github.com/iris-hep/func_adl_xAOD

extra:
  recipe-maintainers:
    - gordonwatts
    - matthewfeickert
